apiVersion: devopstoolkitseries.com/v2
kind: Cluster
metadata:
  name: a-team
spec:
  id: a-team
  crossplane:
    compositionSelector:
      matchLabels:
        provider: azure
        cluster: aks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    namespaces:
      - dev
      - production
    usage:
      # Usage is still in `alpha` and needs to be enabled by add `--set args='{"--enable-usages"}'` to `helm install`.
      enabled: true
