apiVersion: devopstoolkit.ai/v2
kind: Cluster
metadata:
  name: a-team
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        provider: azure
        cluster: aks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    namespaces:
      - dev
      - production
