package apiextensionscrossplaneio


// Type specifies where the value for a label comes from.
type CompositionSpecEnvironmentEnvironmentConfigsSelectorMatchLabelsType string

const (
	// FromCompositeFieldPath.
	CompositionSpecEnvironmentEnvironmentConfigsSelectorMatchLabelsType_FROM_COMPOSITE_FIELD_PATH CompositionSpecEnvironmentEnvironmentConfigsSelectorMatchLabelsType = "FROM_COMPOSITE_FIELD_PATH"
	// Value.
	CompositionSpecEnvironmentEnvironmentConfigsSelectorMatchLabelsType_VALUE CompositionSpecEnvironmentEnvironmentConfigsSelectorMatchLabelsType = "VALUE"
)

