apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: dot-kubernetes
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic (@vfarcic)
    meta.crossplane.io/source: github.com/vfarcic/crossplane-kubernetes
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Fully operational Kubernetes clusters in AWS (EKS), Google Cloud Platform (GKE), and Azure (AKS)
    meta.crossplane.io/readme: A Configuration package that defines a CompositeCluster and ClusterClaim types that can be used to create and provision Kubernetes fully operational clusters in AWS (EKS), Google Cloud Platform (GKE), and Azure (AKS).
spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-eks
    version: ">=v0.36.0"
  - provider: xpkg.upbound.io/upbound/provider-aws-iam
    version: ">=v0.36.0"
  - provider: xpkg.upbound.io/upbound/provider-aws-ec2
    version: ">=v0.36.0"
  - provider: xpkg.upbound.io/upbound/provider-azure-containerservice
    version: ">=v0.33.0"
  - provider: xpkg.upbound.io/upbound/provider-gcp-container
    version: ">=v0.33.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
    version: ">=v0.1.4"
  - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
    version: ">=v0.4.0"
  - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
    version: ">=v0.2.1"
  # - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
  #   version: ">=v0.14.0"
  # - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
  #   version: ">=v0.11.0"
