apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: clusters.devopstoolkit.ai
  labels:
    idp: 'true'
spec:
  defaultCompositionRef:
    name: cluster-aws
  group: devopstoolkit.ai
  scope: Namespaced
  names:
    kind: Cluster
    plural: clusters
  versions:
  - name: v2
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                description: Parameters used to customize the cluster
                type: object
                properties:
                  version:
                    description: The Kubernetes version for the cluster.
                    type: string
                  nodeSize:
                    description: The size of the nodes; small, medium, large.
                    type: string
                    default: small
                    enum:
                    - small
                    - medium
                    - large
                  minNodeCount:
                    description: The minimum number of nodes.
                    type: integer
                    default: 1
                  namespaces:
                    description: List of Namespaces that should be created in the cluster
                    type: array
                    default:
                    - dev
                    - production
                    items:
                      type: string
                  gpu:
                    description: GPU node pool configuration for AI/ML workloads
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      nodeSize:
                        description: The size of the GPU nodes; small, medium, large.
                        type: string
                        default: small
                        enum:
                        - small
                        - medium
                        - large
                    required: []
                  apps:
                    type: object
                    description: List of apps that should be installed in the cluster
                    properties:
                      crossplane:
                        description: Install Crossplane
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      argocd:
                        description: Install Argo CD
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          host:
                            type: string
                            default: acme.com
                          repoURL:
                            type: string
                            default: https://github.com/vfarcic/SOMETHING
                          destinationNamespace:
                            type: string
                            default: argo-cd
                          sourcePath:
                            type: string
                            default: '.'
                        required: []
                      openfunction:
                        description: Install OpenFunction
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      dapr:
                        description: Install Dapr. Do not enable it if OpenFunction is enabled since it comes with Dapr.
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      traefik:
                        description: Install Traefik.
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      nvidia:
                        description: Install NVIDIA GPU Operator for GPU driver and device plugin management. Required for AWS (EKS) and Azure (AKS). Optional for Google (GKE) where drivers and device plugin are pre-installed.
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      vllm:
                        description: Install vLLM Production Stack for LLM inference serving
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                        required: []
                      externalSecrets:
                        description: Install External Secrets Operator (ESO)
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          store:
                            description: Whether to create secret store. If `true`, `creds` field needs to be set as well.
                            type: boolean
                          googleCredentialsKey:
                            description: The key with Google credentials in the secret. Works only with clusters in Google Cloud.
                            type: string
                          awsAccessKeyIDKey:
                            description: The key with Access Key ID in the secret. Works only with clusters in AWS.
                            type: string
                            default: accessKeyID
                          awsSecretAccessKeyKey:
                            description: The key with Secret Access Key in the secret. Works only with clusters in AWS.
                            type: string
                            default: secretAccessKey
                          azureVaultUrl:
                            description: The URL of Azure Vault. Works only with clusters in Azure.
                            type: string
                          secrets:
                            description: List of secrets to be created from the secret store. The `store` parameter must be set to `true` for this feature to work.
                            type: array
                            items:
                              type: object
                              properties:
                                fromSecret:
                                  description: The name or the key of secret in the external secret store
                                  type: string
                                toSecret:
                                  description: The name of the secret
                                  type: string
                                toNamespace:
                                  description: The namespace of the secret
                                  type: string
                                type:
                                  description: The type of the secret
                                  type: string
                                  default: Opaque
                              required:
                              - fromSecret
                              - toSecret
                              - toNamespace
                  creds:
                    description: The secret with hyperscaler credentials.
                    type: object
                    properties:
                      name:
                        description: The name of the secret
                        type: string
                      namespace:
                        description: The namespace of the secret
                        type: string
                        default: crossplane-system
                      keys:
                        description: The keys in the secret
                        type: array
                        items:
                          type: string
                    required:
                    - name
                    - namespace
                    - keys
                required:
                - nodeSize
            required:
            - parameters
          status:
            type: object
            properties:
              clusterName:
                description: The name of the cluster.
                type: string
              controlPlaneStatus:
                description: The status of the control plane.
                type: string
              nodePoolStatus:
                description: The status of the node pool.
                type: string
              field1:
                description: A placeholder
                type: string
    additionalPrinterColumns:
    - name: clusterName
      type: string
      jsonPath: '.status.clusterName'
    - name: controlPlane
      type: string
      jsonPath: '.status.controlPlaneStatus'
    - name: nodePool
      type: string
      jsonPath: '.status.nodePoolStatus'
